---
# tasks file for mysql_db

- name: Install mysql-server repository
  yum:
    name: "http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm"
    state: present

- name: Install mysql-server
  yum:
    name: "{{item}}"
    state: present #installed
  with_items:
      - "mysql-server"
      - "mysql-devel"

- name: Create MySql configuration file
  copy:
    content:  |
        [client]
        user=root
        password="{{ db_user_password }}"
    dest: "/etc/.my.cnf"

- name: Start MySQL Service
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Install mysql-python package
  yum:
    name: MySQL-python
    state: present

- name: Install pip
  yum:
    name: "python-pip"
    state: present


- name: Create application Database
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: Create Database user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_user_password }}"
    priv: '*.*:ALL'
    state: present
    host: '%'
